.\" Convert with groff:
.\" groff -m man -T xhtml deconwolf.man1 > deconwolf_man.html

.Dd Nov 12, 2021
.Dt DECONWOLF 1
.Sh NAME
.Nm deconwolf
.Nd Deconvolve wide-field microscopy images
.Sh DESCRIPTION
.Nm DECONWOLF
is an open source software that provides two binaries:
.Nm dw
to deconvolve wide field images, and
.Nm dw_bw
to generate point spread functions according to the Born-Wolf model.
.Sh NOTES
.Nm Web page
http://www.elgw/deconwolf/
